/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import business_logic.Controller;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kris
 */
public class customersFrame extends javax.swing.JFrame {
    
    Controller controller;
    private LinkedList<String> customers_fields;


    /**
     * Creates new form customersFrame
     * @param controller
     */
    public customersFrame(Controller controller) {
        this.customers_fields = new LinkedList<>();
        this.controller = controller;
        customers_fields.add("ID");
        customers_fields.add("Name");
        customers_fields.add("Address");
        initComponents();        
        populate_customer_table();
    }

    private void populate_customer_table(){
        this.customers_table.setModel(new DefaultTableModel(new Object[][]{},customers_fields.toArray()));
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        search_field = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        rent_car_button = new javax.swing.JButton();
        rented_cars_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customers_table = new javax.swing.JTable();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_fieldActionPerformed(evt);
            }
        });

        search_button.setText("Search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        rent_car_button.setText("Rent Car");
        rent_car_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rent_car_buttonActionPerformed(evt);
            }
        });

        rented_cars_button.setText("Rented Cars");
        rented_cars_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rented_cars_buttonActionPerformed(evt);
            }
        });

        customers_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Telephone", "Address"
            }
        ));
        jScrollPane1.setViewportView(customers_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rent_car_button, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(rented_cars_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_button)
                    .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rent_car_button)
                    .addComponent(rented_cars_button))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        try {
            
            Object[][] customers=controller.findCustomers(search_field.getText());
            customers_table.setModel(new DefaultTableModel(customers,customers_fields.toArray()));                
        }
        catch(Exception exp) {
                System.out.println("error"+exp.getMessage());    
        }
    }//GEN-LAST:event_search_buttonActionPerformed

    private void search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_fieldActionPerformed

    private void rent_car_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rent_car_buttonActionPerformed
        Object o;
        int row = customers_table.getSelectedRow();
        if(row>=0){
            o=customers_table.getValueAt(row, 0);
            controller.setTab(0);             // set tab to find
            ManageRentalFrame rentalFrame = new ManageRentalFrame(controller, (String)o);                   
            rentalFrame.setVisible(true);
        }
    }//GEN-LAST:event_rent_car_buttonActionPerformed

    private void rented_cars_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rented_cars_buttonActionPerformed
        Object o;
        int row = customers_table.getSelectedRow();
        if(row>=0){
            o=customers_table.getValueAt(row, 0);
            controller.setTab(1);             // set tab to rented
            ManageRentalFrame rentalFrame = new ManageRentalFrame(controller, (String)o);            
            rentalFrame.setVisible(true);
        }
    }//GEN-LAST:event_rented_cars_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customers_table;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rent_car_button;
    private javax.swing.JButton rented_cars_button;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_field;
    // End of variables declaration//GEN-END:variables
}
